sudo: required
services: 
    - docker

before_install:
    - docker build -t carljetter/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run carljetter/react-test npm run test  -- --coverage

after_success:
    
    - docker build -t carljetter/multi-client ./client
    - docker build -t carljetter/multi-server ./server
    - docker build -t carljetter/multi-nginx ./nginx
    - docker build -t carljetter/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take and push to docker hub
    - docker push carljetter/multi-client
    - docker push carljetter/multi-server
    - docker push carljetter/multi-nginx
    - docker push carljetter/multi-worker




